server:
  port: 8600
spring:
  application:
    name: example-webflux-provider
  zipkin:
    base-url: http://localhost:9411/
#  datasource:
#    url: jdbc:mysql://172.16.7.14:3306/zero_smart_home?characterEncoding=utf-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
    default-property-inclusion: non_null

eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10
#    appname: ${spring.application.name}
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
